spring:
  profiles:
    active: prod
---
spring:
  profiles: test
  application:
    name: MsConfigClient
server:
  port: 8081
flag: 1231

---
spring:
  profiles: prod
  application:
    name: MsConfigClient
server:
  port: 8088
