spring:
  profiles:
    active: prod
---
spring:
  profiles: test
  application:
    name: MsConfigClient
server:
  port: 8081
flag: dddd222

---
spring:
  profiles: prod
  application:
    name: MsConfigClient
server:
  port: 8088
