spring:
  profiles:
    active: prod
---
spring:
  profiles: test
  application:
    name: dddddddddddddd
server:
  port: 8081
flag: 123
---
spring:
  profiles: prod
  application:
    name: tulingvip05-ms-prod
server:
  port: 8088
